### ISSUE TITLE
A couple of changes that you might need to make

### ISSUE THREAD

**Issue by chilas** [iamraphson/DEV-TV#2]
Hey Ayeni, nice work.
Here are a couple of changes that might be worth making. 

> These are personal opinions though  
- Force a redirect from https:// to http:// as it breaks the entire page.
- The menus don't have to be all uppercase.
- Hide the first section in mobile view.

**Comment by iamraphson** [comment]
@chilas thanks for feedback...i will look into this ASAP...

**Comment by iamraphson** [comment]
Dear @chilas 

Thanks for your suggestion,bro. i have fixed all the issues,you can check it out

**Comment by chilas** [comment]
Nice. I noticed the changes. Some other cosmetic changes you'd like to make 
- The icons for every menu shouldn't all be the same
- Account and Account setting should only be shown when the user is logged in.

**Comment by iamraphson** [comment]
@chilas thanks..
- for the menu icon,i make the children icon be same as the parent icon..
- for account and account setting,fixed the issue...

**Comment by chilas** [comment]
@iamraphson Nice one.
